### ISSUE TITLE
Agregar fecha a partidos

### ISSUE THREAD

**Issue by rotvulpix** [rotvulpix/campeonato-irregular#1]
En Listado de Partidos por fecha, únicamente se despliegan los equipos. Es necesaria la información del momento en que se juega el partido.

**Comment by bryanjhv** [comment]
¿En qué formato debería mostrarse la fecha? Sugiero que sea mostrado como: **dd/MM/yyyy hh:mm a**.

**Comment by rotvulpix** [comment]
Preferiría la hora en formato de 24, sugiero usar angular-moment (acabo de agregarla como dependencia y al modulo angular)

**Comment by rotvulpix** [comment]
closed at 5162754
